#
# /etc/pacman.conf - NovaOS
#
# - Arch repos enabled (core, extra, multilib, multilib-testing)
# - NovaOS overlay repo enabled for novaos-* packages
# - AUR helper tools (paru/yay) shipped on the ISO, but AUR runs at runtime
#

[options]
HoldPkg           = pacman glibc
Architecture      = auto
CheckSpace
ParallelDownloads = 8
SigLevel          = Required DatabaseOptional
LocalFileSigLevel = Optional
#DisableDownloadTimeout
ILoveCandy

#[testing]
#Include = /etc/pacman.d/mirrorlist

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

#[core-testing]
#Include = /etc/pacman.d/mirrorlist

#[extra-testing]
#Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

#[multilib-testing]
#Include = /etc/pacman.d/mirrorlist

[novaos]
SigLevel = Optional TrustAll
Server   = https://github.com/salom600/NovaOS/releases/download/repo/$arch
Server   = file:///var/cache/novaos/repo/$arch
