[AutoStart]
Enabled=true

[Daemon]
WatchDesktop=true
AutoUpdate=true

[Backend]
Type=flatpak
AutoUpdate=true
CacheDuration=600

[Sources]
ArchExtra=true
ArchCore=true
AUR=true
Flathub=true
NovaOSAppStore=true
