title    NovaOS Live (Safe Graphics - nomodeset, software rendering)
linux    /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux
initrd   /%INSTALL_DIR%/boot/intel-ucode.img
initrd   /%INSTALL_DIR%/boot/amd-ucode.img
initrd   /%INSTALL_DIR%/boot/x86_64/initramfs-linux.img
options  archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% nomodeset i915.modeset=0 nouveau.modeset=0 nvidia_drm.modeset=0 novaos.session=x11
