title    NovaOS Live (Legacy CPU - linux-lts kernel for older hardware)
linux    /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux-lts
initrd   /%INSTALL_DIR%/boot/intel-ucode.img,/%INSTALL_DIR%/boot/amd-ucode.img,/%INSTALL_DIR%/boot/x86_64/initramfs-linux-lts.img
options  archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% nvidia_drm.modeset=1 nvidia_drm.fbdev=1 modprobe.blacklist=nouveau novaos.session=x11
