title    NovaOS Live (Legacy GPU - 2009-2015 Intel/AMD/Nvidia)
linux    /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux-lts
initrd   /%INSTALL_DIR%/boot/intel-ucode.img,/%INSTALL_DIR%/boot/amd-ucode.img,/%INSTALL_DIR%/boot/x86_64/initramfs-linux-lts.img
options  archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% nvidia_drm.modeset=1 modprobe.blacklist=nouveau i915.enable_guc=0 i915.enable_fbc=0 novaos.session=x11
