[Icon Theme]
Name=NovaOS-Crystal
Name[ar]=كريستال نوفا أو إس
Comment=Crystal glass icons for NovaOS
Comment[ar]=أيقونات زجاجية كريستالية لنوفا أو إس
Inherits=breeze-dark,papirus-dark,Tela-circle,Adwaita,hicolor
Directories=16x16,22x22,32x32,48x48,64x64,128x128,scalable

[16x16]
Size=16
Type=Fixed

[22x22]
Size=22
Type=Fixed

[32x32]
Size=32
Type=Fixed

[48x48]
Size=48
Type=Fixed

[64x64]
Size=64
Type=Fixed

[128x128]
Size=128
Type=Scalable
MinSize=64
MaxSize=256

[scalable]
Size=48
Type=Scalable
MinSize=8
MaxSize=512
Context=Applications
